### ISSUE TITLE
未定义函数或变量 'mag2'

### ISSUE THREAD

**Issue by Jerry-Jincheng** [eezkni/ESIM#1]
当前调用ESIM时会出现函数缺失，但是目录下有mag2.mexw64文件
使用的环境是Ubuntu 16.04

**Comment by eezkni** [comment]
mag2.mexw64 文件是在windows环境下编译的文件，请在windows环境下使用 ESIM

**Comment by Jerry-Jincheng** [comment]
可以提供一下mag2源文件吗？ 这样我可以自己用mex 在ubuntu环境下编译一下

**Comment by eezkni** [comment]
因为一些合作的原因，我们不能提供mag2的源文件

**Comment by Jerry-Jincheng** [comment]
好的， 了解了，谢谢~
